#
# Makefile
#
# Kaleb Riley
# 
# Commands neccessary to successfullly compile fifteens Source
#

fifteen: fifteen.c
	clang -ggdb3 -O0 -std=c99 -Wall -Werror -o fifteen fifteen.c -lcs50 -lm

clean:
	rm -f *.o a.out core fifteen
